= Advent of Code 2022

Personal repo for https://adventofcode.com/2022/.

Main goal is practicing new languages, just getting things to work.

== Lessons learnt

* Day 1
** IntelliJ plugin can support multiple Rust projects under a root directory.
Just "attach" them selecting the `Cargo.toml` file.** `unwrap` causes move.
Can't unwrap the same reference twice.
* Day 2
** Use `regex` to validate input valid lines.
* Day 3
** Writing unit tests for TDD approach.
IntelliJ can run & debug tests normally same as Java.
** Abstracting char as a struct required (done for exercising, in this case it adds code and complexity.
Hoping the 0-cost-abstraction promise is true):
*** Derive Debug for printing the Vector containing it
*** Implement PartialEq trait to use `Vec::contains`
* Day 4
** A method can return multiple values, and that tuple CAN'T be passed to a method directly.
** Practice with '?' operand: it cannot be used for quick replacement of unwrap for tests :'(
** Beware using constructor without named args.
If the var name is the same, order is not respected.
* Day 5
** Using "collect" to aggregate data.
** String split is not very useful, does not allow to use regex.
** Compile works in mysterious ways
*** Both this compile and not sure if there's a difference.
+
----
let number_value:u32 = (&line[start_match..i]).parse().unwrap();
let number_value:u32 = line[start_match..i].parse().unwrap();
----
*** Vec type can be inferred from later code. No need to worry about compilation errors on declaration.
*** Type alias can be used for readability and type safety.
* Need to pay attention when using HashMap, it distinguishes between `get` and `get_mut` if you want to modify the value.
